// react/Alert.jsx
import React, { Component } from "react";

const list = [
	{type: 'primary', cls: 'bg-blue-500 text-white shadow flex'},
	{type: 'danger', cls: 'bg-red-500 text-white shadow flex'},
	{type: 'success', cls: 'bg-green-500 text-white shadow flex'},
	{type: 'warning', cls: 'bg-yellow-500 text-white shadow flex'},
	{type: 'dark', cls: 'bg-black text-white shadow flex'},
	{type: 'light', cls: 'bg-white text-black border border-gray-200 flex'},
	{type: 'secondary', cls: 'bg-gray-200 text-black border border-gray-300 flex'},
]

class Alert extends Component{
  constructor(props){
    super(props)
    this.state = {
      id: 'alert-' + Math.floor(Math.random() * 100000),
      cls: ''
    }
  }
  _type(){
    return list.find((d) => d.type === this.props.type)
  }
  close(){
    this.setState({cls: this.state.cls.replace('flex', 'hidden')})
  }
  componentDidMount(){
    const props = this.props;
    let type    = this._type();
    if(type){
      this.setState({ cls: type.cls })
    }
    if (props.size) {
      switch (props.size) {
        case "sm":
          type.cls = type.cls + " p-2"
          break;
        case "md":
            type.cls = type.cls + " p-3"
          break;
        case "lg":
            type.cls = type.cls + " p-4"
          break;
        default:
          break;
      }
    }
    if (!props.size) {
      this.setState({ cls: type.cls + " p-3" });
    }
    if(props.open) {
      type.cls = type.cls.replace('hidden', 'flex')
    }
    if(!props.open) {
      type.cls = type.cls.replace('flex', 'hidden')
    }
    this.setState({cls: type.cls})
  }
  render(){
    const props = this.props;
    return(
      <div id={this.state.id} className={this.state.cls}>
        <p className="w-full">{props.children}</p>
        <span className="cursor-pointer" onClick={e => this.close()}>
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </span>
      </div>
    )
  }
}

export default Alert

// src/components/form/Alert.vue
<template>
	<div v-if="type == 'error'" :id="'alert-' + id" data-ui="alert" class="bg-red-500 p-3 shadow text-white flex">
		<p class="w-full">{{txt}}</p>
		<span @click="handle" class="cursor-pointer">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
			</svg>
		</span>
	</div>
	<div v-if="type == 'success'" :id="'alert-' + id" data-ui="alert" class="bg-green-500 p-3 shadow text-white flex">
		<p class="w-full">{{txt}}</p>
		<span @click="handle" class="cursor-pointer">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
			</svg>
		</span>
	</div>
	<div v-if="type == 'warning'" :id="'alert-' + id" data-ui="alert" class="bg-yellow-500 p-3 shadow text-white flex">
		<p class="w-full">{{txt}}</p>
		<span @click="handle" class="cursor-pointer">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
			</svg>
		</span>
	</div>
	<div v-if="type == 'dark'" :id="'alert-' + id" data-ui="alert" class="bg-black p-3 shadow text-white flex">
		<p class="w-full">{{txt}}</p>
		<span @click="handle" class="cursor-pointer">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
			</svg>
		</span>
	</div>
	<div v-if="type == 'light'" :id="'alert-' + id" data-ui="alert" class="bg-white p-3 shadow text-black flex border">
		<p class="w-full">{{txt}}</p>
		<span @click="handle" class="cursor-pointer">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
			</svg>
		</span>
	</div>
	<div v-if="type == 'secondary'" :id="'alert-' + id" data-ui="alert" class="bg-gray-500 p-3 shadow text-white flex">
		<p class="w-full">{{txt}}</p>
		<span @click="handle" class="cursor-pointer">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
			</svg>
		</span>
	</div>
</template>
<script>
export default{
	name: 'Alert',
	emits: ['update:txt'],
	props: {
		txt: {
			type: String,
			required: true
		},
		open: {
			type: Boolean,
			required: true
		},
		type: {
			type: String,
			required: true
		}
	},
	data(){
		return{
			id: ''
		}
	},
	mounted(){
		this.id = Math.floor(Math.random() * 10000)
	},
	watch: {
		open(value){
			const el = document.querySelector(`#alert-${this.id}`)
			if(value){
				el.classList.remove('hidden')
			}
		}
	},
	methods: {
		handle(){
			const el = document.querySelector(`#alert-${this.id}`)
			if(el.classList.contains('hidden')){
				el.classList.remove('hidden')
			}else{
				el.classList.add('hidden')
			}
		}
	}
}
</script>
