// react/Alert.jsx
import React, { Component } from "react";

const list = [
	{type: 'primary', cls: 'bg-blue-500 text-white shadow flex'},
	{type: 'danger', cls: 'bg-red-500 text-white shadow flex'},
	{type: 'success', cls: 'bg-green-500 text-white shadow flex'},
	{type: 'warning', cls: 'bg-yellow-500 text-white shadow flex'},
	{type: 'dark', cls: 'bg-black text-white shadow flex'},
	{type: 'light', cls: 'bg-white text-black border border-gray-200 flex'},
	{type: 'secondary', cls: 'bg-gray-200 text-black border border-gray-300 flex'},
]

class Alert extends Component{
  constructor(props){
    super(props)
    this.state = {
      id: 'alert-' + Math.floor(Math.random() * 100000),
      cls: ''
    }
  }
  _type(){
    return list.find((d) => d.type === this.props.type)
  }
  close(){
    this.setState({cls: this.state.cls.replace('flex', 'hidden')})
  }
  componentDidMount(){
    const props = this.props;
    let type    = this._type();
    if(type){
      this.setState({ cls: type.cls })
    }
    if (props.size) {
      switch (props.size) {
        case "sm":
          type.cls = type.cls + " p-2"
          break;
        case "md":
            type.cls = type.cls + " p-3"
          break;
        case "lg":
            type.cls = type.cls + " p-4"
          break;
        default:
          break;
      }
    }
    if (!props.size) {
      this.setState({ cls: type.cls + " p-3" });
    }
    if(props.open) {
      type.cls = type.cls.replace('hidden', 'flex')
    }
    if(!props.open) {
      type.cls = type.cls.replace('flex', 'hidden')
    }
    this.setState({cls: type.cls})
  }
  render(){
    const props = this.props;
    return(
      <div id={this.state.id} className={this.state.cls}>
        <p className="w-full">{props.children}</p>
        <span className="cursor-pointer" onClick={e => this.close()}>
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </span>
      </div>
    )
  }
}

export default Alert

// src/components/Alert.vue
<template>
	<div :id="id" :class="cls">
		<p class="w-full"><slot></slot></p>
		<span @click="handle" class="cursor-pointer">
			<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
			</svg>
		</span>
	</div>
</template>
<script>
const list = [
	{type: 'primary', cls: 'bg-blue-500 text-white shadow flex'},
	{type: 'danger', cls: 'bg-red-500 text-white shadow flex'},
	{type: 'success', cls: 'bg-green-500 text-white shadow flex'},
	{type: 'warning', cls: 'bg-yellow-500 text-white shadow flex'},
	{type: 'dark', cls: 'bg-black text-white shadow flex'},
	{type: 'light', cls: 'bg-white text-black border border-gray-200 flex'},
	{type: 'secondary', cls: 'bg-gray-200 text-black border border-gray-300 flex'},
]
export default{
	name: 'Alert UI',
	props: {
		open: {
			required: true
		},

		type: {
			type: String, required: true
		},
		bg: {
			type: String, required: false
		},
		color: {
			type: String, required: false
		},
		p: {
			type: String, required: false
		},
		size: {
			type: String, required: false
		},
		role: {
			type: String, required: false
		},
	},
	data(){
		return{
			id: 'alert-' + Math.floor(Math.random() * 100000),
			cls: ' '
		}
	},
	beforeMount(){
		this.open == "false" ? this.cls = this.cls.replace('', ' hidden'): false
		if(this.type !== 'custom'){
			for (var i = 0; i < list.length; i++) {
				if(list[i].type == this.type){
					if(this.size == 'sm'){
						this.cls = this.cls.replace('', ' ' + list[i].cls + ' p-2')
					}
					if(this.size == 'md'){
						this.cls = this.cls.replace('', ' ' + list[i].cls + ' p-3')
					}
					if(this.size == 'lg'){
						this.cls = this.cls.replace('', ' ' + list[i].cls + ' p-4')
					}
					else{
						this.cls = this.cls.replace('', ' ' + list[i].cls + ' p-3')
					}
				}
			}
		}else{
			this.cls = this.cls.replace('', ' flex')
			this.bg ? this.cls = this.cls.replace('', ' bg-' + this.bg): this.cls = this.cls.replace('', ' bg-white')
			this.color ? this.cls = this.cls.replace('', ' text-' + this.color): this.cls = this.cls.replace('', ' text-white')
			this.p ? this.cls = this.cls.replace('', ' p-' + this.p): this.cls = this.cls.replace('', ' p-3')
			this.ring ? this.cls = this.cls.replace('', ' focus:ring-' + this.ring): this.cls = this.cls.replace('', ' focus:ring-gray-200')
			this.sizeRing ? this.cls = this.cls.replace('', ' focus:ring-' + this.sizeRing): this.cls = this.cls.replace('', ' focus:ring')
		}
	},
	watch: {
		open(value){
			const el = document.querySelector(`#${this.id}`)
			if(value == 'false'){
				el.classList.remove('flex')
				el.classList.add('hidden')
			}
			else{
				el.classList.remove('hidden')
				el.classList.add('flex')
			}
		}
	},
	methods: {
		handle(){
			const el = document.querySelector(`#${this.id}`)
			if(el.classList.contains('hidden')){
				el.classList.remove('hidden')
				el.classList.add('flex')
			}else{
				el.classList.remove('flex')
				el.classList.add('hidden')
			}
		}
	}
}
</script>
