// react/Dropdown.jsx
import React from 'react';
import Button from './Button'

function Dropdown(props) {
  const [state, set] = React.useState({
    cls: '',
    open: false,
    clasess: 'hidden'
  });
  React.useEffect(() => {
    if (props.animate) {
      set({
        clasess:
          ' visible transform scale-0 transition duration-200 flex flex-wrap w-full bg-white p-1 border absolute top-0 left-0 mt-12 z-10'
      });
    }
  }, props.animate);
  const handle = e => {
    e.preventDefault();
    if(!state.open){
      set({open: true})
      if(props.animate == 'scale'){
        set({open: true, clasess: 'transform scale-100 transition duration-200 flex flex-wrap w-full bg-white p-1 border absolute top-0 left-0 mt-12 z-10'})
      }
      else{
        set({open: true, clasess: 'flex flex-wrap w-full bg-white p-1 border absolute top-0 left-0 mt-12 z-10'})
      }
    }else{
      set({open: false})
      if(props.animate == 'scale'){
        set({open: false, clasess: ' visible transform scale-0 transition duration-200 flex flex-wrap w-full bg-white p-1 border absolute top-0 left-0 mt-12 z-10'})
      }
      else{
        set({open: false, clasess: 'hidden'})
      }
    }
  };

  return (
    <div className="w-full flex flex-wrap relative">
      <Button w="full" onClick={handle} type="primary">{props.txt}</Button>
      {props.link ? (
        <div className={state.clasess}>
          {props.link.map(data => (
            <Link
              className="p-2 w-full hover:bg-gray-100 transition-all duration-200 z-10 bg-white"
              to={data.link}
            >
              {data.name}
            </Link>
          ))}
        </div>
      ) : (
        <div className={state.clasess}>{props.children}</div>
      )}
    </div>
  );
}

export default Dropdown;

// src/components/Dropdown.vue
<template>
	<div data-ui="dropdown" class="w-full flex flex-wrap relative">
		<a @click="action" href="/" :class="classNames + ' w-full'">
			{{title}}
		</a>
		<div :class="clasess">
			<router-link v-for="(data, key) in link" v-bind:key="key" :to="{path: data.link}" class="p-2 w-full hover:bg-gray-100 transition-all duration-200 z-10 bg-white">{{data.name}}</router-link>
		</div>
	</div>
</template>
<script>
export default{
	name: 'Dropdown',
	props: {
		title: String,
		link: Array,
		classNames: String,
	},
	data(){
		return{
			clasess: 'hidden',
			open: false
		}
	},
	methods: {
		action(e){
			e.preventDefault()
			if(!this.open){
				this.open = true
				this.clasess = 'flex flex-wrap w-full bg-white p-1 border border-t-0 absolute top-0 left-0 mt-12'
			}else{
				this.open = false
				this.clasess = 'hidden'
			}
		}
	}
}
</script>
