// react/Tabs.jsx
import React from 'react';
import Button from './Button'

function Tabs(props) {
  const [state, set] = React.useState({
    open: ''
  });
  React.useEffect(() => {
    set({
      open: props.default
    });
    console.log(props.default, props[props.default]);
  }, [props.default, props[props.default]]);
  const handle = (e, name) => {
    e.preventDefault();
    if (name !== state.open) {
      set({
        open: name
      });
    }
  };
  return (
    <>
      {props.post === 'x' ? (
        <div>
          <div className="grid grid-flow-col">
            {props.title.map((data, key) => (
              <Button
                onClick={e => handle(e, data.name)}
                key={key}
                type={props.type}
                data-name={data.name}
              >
                {data.title}
              </Button>
            ))}
          </div>
          <div className="body">
            {props.title.map((data, key) => (
              <div key={key}>
                {data.name === state.open ? (
                  <div className={props.noPadding ? 'w-full block border': 'w-full block p-3 border'}>{props[data.name]}</div>
                ) : (
                  <div className="w-full hidden">{props[data.name]}</div>
                )}
              </div>
            ))}
          </div>
        </div>
      ) : (
        false
      )}
      {props.post === 'y' ? (
        <div className="flex">
          <div className="grid grid-flow-row w-1/5">
            {props.title.map((data, key) => (
              <Button
                onClick={handle}
                key={key}
                type={props.type}
                data-name={data.name}
              >
                {data.title}
              </Button>
            ))}
          </div>
          <div className="body w-4/5">
            {props.title.map((data, key) => (
              <div key={key}>
                {data.name === state.open ? (
                  <div className={props.noPadding ? 'w-full block border': 'w-full block p-3 border'}>{props[data.name]}</div>
                ) : (
                  <div className="w-full hidden">{props[data.name]}</div>
                )}
              </div>
            ))}
          </div>
        </div>
      ) : (
        false
      )}
    </>
  );
}

export default Tabs;

// src/components/Tabs.vue
<template>
	<div v-if="post == 'x'" :id="id">
		<div class="grid grid-flow-col">
			<Button @click="toggle" v-for="(data, key) in title" v-bind:key="key" :type="type" :data-name="data.name">{{data.title}}</Button>
		</div>
		<div class="body">
			<div v-for="(data, key) in title" v-bind:key="key">
				<div v-if="data.name == this.open" :class="noPadding ? 'w-full block border': 'w-full block p-3 border'">
					<slot :name="data.name"></slot>
				</div>
				<div v-else class="w-full hidden">
					<slot :name="data.name"></slot>
				</div>
			</div>
		</div>
	</div>
	<div v-if="post == 'y'" :id="id" class="flex">
		<div class="grid grid-flow-row w-1/5">
			<Button @click="toggle" v-for="(data, key) in title" v-bind:key="key" :type="type" :data-name="data.name">{{data.title}}</Button>
		</div>
		<div class="body w-4/5">
			<div v-for="(data, key) in title" v-bind:key="key">
				<div v-if="data.name == this.open" :class="noPadding ? 'w-full block border': 'w-full block p-3 border'">
					<slot :name="data.name"></slot>
				</div>
				<div v-else class="w-full hidden">
					<slot :name="data.name"></slot>
				</div>
			</div>
		</div>
	</div>
</template>
<script>
export default{
	name: 'Tabs UI',
	props: {
		type: {
			type: String,
			required: true
		},
		title: {
			type: Array,
			required: true
		},
		default: {
			type: String,
			required: true
		},
		post: {
			type: String,
			required: true
		},
		noPadding: {
			type: Boolean,
			required: false
		},
	},
	data(){
		return{
			id: 'tabs-' + Math.floor(Math.random() * 100000),
			defaultOpen: '',
			open: ''
		}
	},
	beforeMount(){
		this.open = this.default
	},
	methods: {
		toggle(e){
			e.preventDefault()
			if(e.target.dataset.name !== this.open){
				this.open = e.target.dataset.name
			}
		}
	}
}
</script>
